ORMs/CRUDelicious/Models/CRUDeliciousContext.cs
using Microsoft.EntityFrameworkCore;

namespace CRUDelicious.Models
{
    public class CRUDeliciousContext : DbContext
    {
        public CRUDeliciousContext(DbContextOptions options) : base(options) { }

        // for every model / entity that is going to be part of the db
        // the names of these properties will be the names of the tables in the db
        public DbSet<Dish> Dishes { get; set; }

    }
}

ORMs/CRUDelicious/Models/Dish.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace CRUDelicious.Models
{
    public class Dish
    {
        [Key] //Primary Key
        public int DishId { get; set; }
        
        [Required(ErrorMessage = "is required.")]
        [MinLength(2, ErrorMessage = "Must be more than 2 characters.")]
        [MaxLength(45, ErrorMessage = "Must be less than 45 characters.")]
        public string Name { get; set; }

        [Required(ErrorMessage = "is required.")]
        [MinLength(2, ErrorMessage = "Must be more than 2 characters.")]
        [MaxLength(45, ErrorMessage = "Must be less than 45 characters.")]
        public string Chef { get; set; }

        [Required(ErrorMessage = "is required.")]
        [Range(0,6, ErrorMessage = "Must be more than 0 or less than 6.")]
        public int Tastiness { get; set; }
        
        [Required(ErrorMessage = "is required.")]
        [Range(0,999999999, ErrorMessage = "Must be more than 0 Calories.")]
        public int Calories { get; set; }
        
        [Required(ErrorMessage = "is required.")]
        [MinLength(2, ErrorMessage = "Must be more than 2 characters.")]
        public string Description { get; set; }
        public DateTime CreatedAt { get; set; } = DateTime.Now;
        public DateTime UpdatedAt { get; set; } = DateTime.Now;
    }
}

ORMs/CRUDelicious/Models/ErrorViewModel.cs
using System;

namespace CRUDelicious.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ORMs/CRUDelicious/Controllers/DishesController.cs
using System;
using System.Linq;
using CRUDelicious.Models;
using Microsoft.AspNetCore.Mvc;

namespace CRUDelicious.Controllers
{
    public class DishesController : Controller
    {
        private CRUDeliciousContext db;
        public DishesController(CRUDeliciousContext context)
        {
            db = context;
        }

        // 1. handles GET request to DISPLAY the form used to create a new Post
        [HttpGet("/new")]
        public IActionResult New()
        {
            return View("New");
        }

        [HttpPost("/create")]
        public IActionResult Create(Dish newDish)
        {
            if(ModelState.IsValid == false)
            {
                // Go back to the form so errror messages are displayed.
                return View("New");
            }

            db.Dishes.Add(newDish);

            db.SaveChanges();
            return RedirectToAction("Index","Home");
        }

        [HttpGet("/edit/{dishId}")]
        public IActionResult Details (int dishId)
        {
            Dish dish = db.Dishes.FirstOrDefault(d => d.DishId == dishId);

            if (dish == null)
            {
                return RedirectToAction("Index","Home");
            }

            return View("Details", dish);
        }

        [HttpPost("/edit/{dishId}/delete")]
        public IActionResult Delete(int dishId)
        {
            Dish dish = db.Dishes.FirstOrDefault(d => d.DishId == dishId);
            
            if (dish == null)
            {
                RedirectToAction("Index","Home");
            }

            db.Dishes.Remove(dish);
            db.SaveChanges();
            return RedirectToAction("Index","Home");
        }

        [HttpGet("/edit/{dishId}/edit")]
        public IActionResult Edit(int dishId)
        {
            Dish dish = db.Dishes.FirstOrDefault(d => d.DishId == dishId);

            if (dish == null)
            {
                return RedirectToAction("Index","Home");
            }

            return View("Edit", dish);
        }

        [HttpPost("/edit/{dishId}/update")]
        public IActionResult Update(int dishId, Dish editedDish)
        {
            if (ModelState.IsValid == false)
            {
                editedDish.DishId = dishId;
                return View("Edit", editedDish);
            }

            Dish dbDish = db.Dishes.FirstOrDefault(d => d.DishId == dishId);

            if (dbDish == null)
            {
                return RedirectToAction("Index","Home");
            }

            dbDish.Name = editedDish.Name;
            dbDish.Chef = editedDish.Chef;
            dbDish.Tastiness = editedDish.Tastiness;
            dbDish.Calories = editedDish.Calories;
            dbDish.Description = editedDish.Description;
            dbDish.UpdatedAt = DateTime.Now;
            
            db.Dishes.Update(dbDish);
            db.SaveChanges();

            return RedirectToAction("Details", new { dishId = dishId});
        }
    }
}

ORMs/CRUDelicious/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CRUDelicious.Models;

namespace CRUDelicious.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private CRUDeliciousContext db;
        public HomeController(CRUDeliciousContext context)
        {
            db = context;
        }

        [HttpGet("")]
        public IActionResult Index()
        {
            List<Dish> allDishes = db.Dishes.ToList();
            return View("Index", allDishes);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ORMs/CRUDelicious/Views/Dishes/Details.cshtml
@model Dish

<div class="w-75 mx-auto">

    <h4 class="text-center">@Model.Name</h4>
    <p class="text-center">@Model.Chef</p>

    <div class="border-top border-dark text-left pt-4">
        <p>@Model.Description</p>
        
        <div>
            <p>Calories: @Model.Calories</p>
            <p>Tastiness: @Model.Tastiness</p>
        </div>

        <div class="row justify-content-around">
            <form asp-controller="Dishes" asp-action="Delete" asp-route-dishId="@Model.DishId" method="POST">
                <button class="btn btn-outline-danger btn-small">Delete</button>
            </form>

            <a asp-controller="Dishes" asp-action="Edit" asp-route-dishId="@Model.DishId" class="btn btn-sm btn-outline-warning ml-2">Edit</a>
        </div>
    </div>

</div>

ORMs/CRUDelicious/Views/Dishes/Edit.cshtml
@model Dish

<div class="w-75 mx-auto">
    <h4 class="text-center">Edit a new Dish!</h4>

    <form class="d-flex d-flex justify-content-between align-items-start mt-5" asp-controller="Dishes" asp-action="Update" asp-route-dishId="@Model.DishId" method="POST">

        <div>
            <label asp-for="Chef"></label>
            <span asp-validation-for="Chef" class="text-danger font-weight-bold"></span>
            <input asp-for="Chef" class="form-control" />

            <label asp-for="Name"></label>
            <span asp-validation-for="Name" class="text-danger font-weight-bold"></span>
            <input asp-for="Name" class="form-control" />

            <label asp-for="Calories"></label>
            <span asp-validation-for="Calories" class="text-danger font-weight-bold"></span>
            <input asp-for="Calories" class="form-control" />
        </div>

        <div>
            <label asp-for="Tastiness"></label>
            <select asp-for="Tastiness">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
            </select>
        </div>

        <div>
            <label asp-for="Description"></label>
            <span asp-validation-for="Description" class="text-danger font-weight-bold"></span>
            <textarea asp-for="Description" class="form-control"></textarea>
            <button class="btn btn-sm btn-outline-dark mt-3">Edit Dish</button>
        </div>

    </form>
    
</div>

ORMs/CRUDelicious/Views/Dishes/New.cshtml
@model Dish

<div class="w-75 mx-auto">
    <h4 class="text-center">Add a new Dish!</h4>

    <form class="d-flex d-flex justify-content-between align-items-start mt-5" asp-controller="Dishes" asp-action="Create" method="POST">

        <div>
            <label asp-for="Chef"></label>
            <span asp-validation-for="Chef" class="text-danger font-weight-bold"></span>
            <input asp-for="Chef" class="form-control" />

            <label asp-for="Name"></label>
            <span asp-validation-for="Name" class="text-danger font-weight-bold"></span>
            <input asp-for="Name" class="form-control" />

            <label asp-for="Calories"></label>
            <span asp-validation-for="Calories" class="text-danger font-weight-bold"></span>
            <input asp-for="Calories" class="form-control" />
        </div>

        <div>
            <label asp-for="Tastiness"></label>
            <select asp-for="Tastiness">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
            </select>
        </div>

        <div>
            <label asp-for="Description"></label>
            <span asp-validation-for="Description" class="text-danger font-weight-bold"></span>
            <textarea asp-for="Description" class="form-control"></textarea>
            <button class="btn btn-sm btn-outline-dark mt-3">Add Dish</button>
        </div>

    </form>
    
</div>

ORMs/CRUDelicious/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUDelicious</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CRUDelicious</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dishes" asp-action="New">Add a Dish</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CRUDelicious - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>